(defun recognize-ab*c (symbols &optional(state "s0"))
	(cond ((null symbols) (if (equal state "s2") T nil))
	      ((atom symbols) (error "atom"))
	      (cond ((equal state "s0") (if (equal (car symbols) 'a)
						(recognize-ab*c (cdr symbols) "s1") 
						nil))
                    ((equal state "s1") (cond ((equal (car symbols) 'b)
                                                (recognize-ab*c (cdr symbols) "s1"))
	                                      ((equal (car symbols) 'c)
                                                (recognize-ab*c (cdr symbols) "s2"))))
		    (T nil)))) 
